FROM rust:1.70.bullseye

# install llvm, used by bindgen
RUN apt-get update && \
    apt-get install -y llvm-dev libclang-dev clang

# download dieharder source and extract from gzipped tarball
# curl: -L follows redirects
# tar: -x extract, -z gzip, -f file
RUN curl -L http://www.phy.duke.edu/~rgb/General/dieharder/dieharder-3.31.1.tgz -o /usr/local/src/dieharder.tgz && \
    tar -xzf /usr/local/src/dieharder.tgz -C /usr/local/src

WORKDIR /usr/src/fuin
COPY . .

RUN cargo install --path .

# used in build.rs to conditionally generate C bindings via bindgen
ENV CARGO_CFG_TEST="true"
CMD ["cargo", "test", "-vv"]